spring:
  data:
    redis:
      database: 0
      host: localhost
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: ''
          min-idle: 0
      password: ''
      port: 6379
      timeout: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root