spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny: 192.168.1.122

  # 访问静态资源需要加上前缀/static/
  mvc:
    static-path-pattern: /static/**
  #    view:
  #      prefix: /WEB-INF/views/
  #      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

#logging:
 # config: classpath:log4j2.xml