# 不通过controller直接访问html:可以通过配置spring.resources.static-locations指定静态资源的位置，此时可以访问http://ip:port/静态资源(如.html .js .css)来访问
spring:
  web:
    resources:
      static-locations: classpath:/templates/
# spring.mvc.static-path-pattern 这个代表访问的时候需要加上前缀/templates/
#  mvc:
#    static-path-pattern: /templates/**