server:
  port: 8089

spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/

socketio:
  host: localhost
  port: 8503
  maxFramePayloadLength: 1048576
  maxHttpContentLength: 1048576
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 10000
  pingTimeout: 60000
  pingInterval: 25000